kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow 
  namespace: automation 
  labels:
    app: airflow
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: airflow 
  template: 
    metadata: 
      labels: 
        app: airflow 
    spec: 
      serviceAccountName: airflow-scheduler
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
        - name: init-db
          resources:
            {}
          image: wilkobets/airflow:latest
          imagePullPolicy: Always
          securityContext: 
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args:          
            - airflow
            - db
            - upgrade
          envFrom:
            - secretRef:
                name: airflow-secret       
      containers:         
        - name: airflow-scheduler 
          image: wilkobets/airflow:latest
          imagePullPolicy: Always
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryKubernetesExecutor"
            - name: AIRFLOW__LOGGING__LOGGING_LEVEL
              value: "WARNING"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE
              value: "/opt/airflow/sync/smart-home-config/workloads/airflow/pod_templates/pod_template_file.yaml"
            - name: AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE
              value: "automation"
            - name: AIRFLOW__CELERY_KUBERNETES_EXECUTOR__KUBERNETES_QUEUE
              value: "kubernetes"
            - name: AIRFLOW__CORE__DAGS_FOLDER 
              value: "/opt/airflow/sync/smart-home-config/workloads/airflow/dags"
            - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL 
              value: "300"
            - name: AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT
              value: "False"
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "True"
            - name: AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
              value: "300"
            - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
              value: "1"
            - name: AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC
              value: "10"
            - name: AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL
              value: "30"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE
              value: "5"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_MAX_OVERFLOW
              value: "5"
          envFrom:
            - secretRef:
                name: airflow-secret
          volumeMounts:
            - name: airflow-logs-pv
              mountPath: /opt/airflow/logs
              readOnly: false
            - name: airflow-resources
              mountPath: "/opt/airflow/sync"
              readOnly: true
          command:
            - airflow
          args:
            - scheduler 
        - name: airflow-webserver
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryKubernetesExecutor"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CORE__DAGS_FOLDER 
              value: "/opt/airflow/sync/smart-home-config/workloads/airflow/dags" 
            - name: AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE 
              value: "automation"
            - name: AIRFLOW__CELERY_KUBERNETES_EXECUTOR__KUBERNETES_QUEUE
              value: "kubernetes"
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "True"
            - name: AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
              value: "Europe/London"
          envFrom:
            - secretRef:
                name: airflow-secret
          volumeMounts:
            - name: config
              mountPath: "/opt/airflow/webserver_config.py"
              subPath: webserver_config.py
              readOnly: true          
            - name: airflow-logs-pv 
              mountPath: /opt/airflow/logs 
          image: wilkobets/airflow:latest
          imagePullPolicy: Always 
          ports: 
            - containerPort: 8080 
          command: 
            - airflow 
          args: 
            - webserver 
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.8
          env:
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_REPO
            value: "https://github.com/cwilko/smart-home-config"
          - name:  GIT_SYNC_DEST
            value: "smart-home-config"
          - name:  GIT_SYNC_ROOT
            value: "/git"
          - name:  GIT_SYNC_ONE_TIME
            value: "false"
          - name:  GIT_SYNC_WAIT
            value: "60"
          volumeMounts:
            - name: airflow-resources
              mountPath: /git
      restartPolicy: Always 
      volumes: 
        - name: config
          configMap:
            name: airflow-config
        - emptyDir: {} 
          name: airflow-resources
        - name: airflow-logs-pv 
          persistentVolumeClaim: 
            claimName: airflow-logs-data
      