---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-fluent-bit
  namespace: iot
  labels:
    helm.sh/chart: fluent-bit-0.55.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "4.2.2"
    app.kubernetes.io/managed-by: Helm
---
# Source: fluent-bit/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.55.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "4.2.2"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
# Source: fluent-bit/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit-fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.55.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "4.2.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit-fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluentbit-fluent-bit
    namespace: iot
---
# Source: fluent-bit/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fluentbit-fluent-bit
  namespace: iot
  labels:
    helm.sh/chart: fluent-bit-0.55.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "4.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluentbit
---
# Source: fluent-bit/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-fluent-bit
  namespace: iot
  labels:
    helm.sh/chart: fluent-bit-0.55.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "4.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: fluentbit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/instance: fluentbit
      annotations:
        checksum/config: 9c95bdd7d0a8a9b508b00125ec218cde5083829b8d106b1ae4c5d11a8c1a7600
    spec:
      
      serviceAccountName: fluentbit-fluent-bit
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
        - name: fluent-bit
          image: "cr.fluentbit.io/fluent/fluent-bit:4.2.2"
          imagePullPolicy: IfNotPresent
          command:
            - /fluent-bit/bin/fluent-bit
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/conf/fluent-bit.conf
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 20m
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/conf
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /var/log/pods
              name: varpods
              readOnly: true
            - mountPath: /etc/machine-id
              name: etcmachineid
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluentbit-fluent-bit
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - hostPath:
            path: /var/log/pods
          name: varpods
        - hostPath:
            path: /etc/machine-id
            type: File
          name: etcmachineid
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
        - effect: NoSchedule
          operator: Exists
