---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-secrets
  namespace: automation
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAd5RUW2QIh7LeOwXtKzxjwuNs2qriZJGyncpyYWlBnhIg9gvizynUkop6yTdL1yPK7PL3rg4o9QnhyntjUXa+v2v1FljTeKwgdXqnJY/nVNV7yK6jSEQ47zAFgLowezuhv289Da6bRCvYK2Wb9oI2nQpPHnhOAjCiG+BsJaPhL5VUwc0A0qwYvguWtWO2U5W+XKYYbzCs75j5UdAVAmrBTzq+h5Y2O9vXFV5XU3HqX3KFU3c9jsO4wDZF2Ha2H6VVa8aWYbmujQtXHOWmCF0G15cKCoQcQRmo8NhK20o8vmQ19owRNRPjy3kZ0ldZciqH6GJ5bhUEuKnumWSTIbAT2KtVbdnvMt/8v+vKXf6pPDPPwgqA2T5wTvmpGh2olDHHsUZR5Cdja6mbCdqkLKXl8eq9CV6+s1WPpKbAQijH1R+16YJnnfdjmae2tn3+ZnRXsgDVCcWYKAHyB3xUkIxccLBaCmvrcwYaYGCiSY82h7RI7uGfmfcfc3d+j+L1MLOz0XPh5CRtztp0xGNDXF6Erpb8pWYjKdZQhXv0wteBartweYi5yka09q+y1G86rsSb6aM/Hn3zSVhwxbx2ieUIp8LxKi7p6ughm6IeT5fhJAzEobfwt7fItGc+1ZWnm7JHScdBIo394DORes2V8G15QnxiB32OoGtRXOTazNdtu0zlvnZeOP2SBwqpAhNYKnZOSM7voqwY=
    GF_SECURITY_ADMIN_USER: AgAHovdieLN5I/nBRd2Rm5EqUost48VKS9vo3tn+jGWBcDacbZTgRZ3uyBWC66NCqL8047xUmnzDYEJgLrPRZGwTaZyZxBgRoWpNlzdacHcGsry+NWcprfkVzVeaPODSRpRLI4BV8Dy0SDw7SIrhGyP5vsqNWXS8k3aaOXOxKFVkYmG3H2zkFMWDdQhEIt34D0li6fPMfepSGVI3bD1vx6fNv52QnHvvbw9j2tx5PjoMoCPLK2PwXvA/8d6vZJ1RMZA4fj0XuWUzxxKfTKNap1gr7o6Kq8Tkw0Shyf+sBM1RcLLC5CqONEwPAD6e5we/JsULmqmhy4gmeQdQ6n3FUSoyDGVp07iWQsuRvbsT8eRWm1qCyFNDh0YhXmZ/QGr4b4kkvFtyDM4xMChoZTLU1LfDuaSZCA+5CCr7JJxeQs83n3wru/wBVEp90gYH+/FiGGpKl+ofqzpKaSbjJWRiBpVIwvZ0CnTRTgkoxf2lanSK3cjiQgGOXHqlA17drzeGCbmtbgPS5Hw2KHfUyb7BA6BfcIIUDrp61WNGysZKMxcEU2Y15FWuTys0PGsLjxTYAm8lfg3MR5De7P2UlkDi6NWCZwOxMBNZ+nRDeR2fbthcmCkVy74LqFFnY2kQ16A4vRqxgGigPSLa+X2iS7LFtw9ta6PLQ+3YPJzxvq0kWLEEwy+gr+K1LRZqkh+CSkY9N6iCMkv8LA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-secrets
      namespace: automation
    type: Opaque
