---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: influxdb-ds-secret
  namespace: automation
spec:
  encryptedData:
    influxdb-datasource.yaml: AgBl7JmVJuKQI7LXWR3tMB/yqSJeZKENl+LKg39N6FVI9L8+XYjTUJLhWHF9yfhanh23tYLsfaMBVJhMeqiqe3GvBWbXig1t0Gb05i0LaDhZIcNLiTD5vyXSUxQNrpqgS5WuOceeN5yY/J9oCC7ybMm1lKCMRNKhRRIu0nOStZqheecJXUABvmL0TE07QcB3FS4qprwYegSGA5CuZQZb9tKZvcI6rW11KgnrGXaWgeS1LUFyeGE0Ul1b4RWBlme4r317Gamv6q/FBtUKRhfgxRNUxVzuuKZNC93YbS4BjrlGo7jg4Qts5xJedW10ixjGJQVyKSuP67Ui37Y7X2uIjdQ/tNlYRyozfqo67fDxGtsBH3hvac4xHmoV8mcryN9Dyg1U5Z3mrtOefApCXEN+oS3IjpWlbjH2Sc8yBakBaN5bmOstUqLn407rLeAI9MJ5D5MdqbgCsFOv+mEz3TTtvpxi4y1pJAeouE8AamQAZZRfuDOsr95BZ3urLWBXF0wZ5AEnQk2CqLwe4nIKAtSjb5nMW9gjQlCLgkZGRaaJl0lTJK4SG6x+TJHFi+x1k3wzAAxBXlB8LOI0RRXeo10/HH03T6nOPoLgwr5BYM0Ywmpy99wqEdcnvJ3K69bxhLXaida6ofoniUKqxIi55ZyyOlFn/QT+/AKModo6jTalT9Lj7UW1FyiSD/7OkqnAXXz9c24cCUlqA4J4I5vgOPmFmh/1dfUu1P/3f2vbJLoPske+c854wm0U77oZ/u9SFnG0Cfv5PkSkuYKGLBP+Rr2pnJp2U8jAyOgrEAbJfn3ABsqMGpzki+n5BEye0IhpFfKAS5cggao8chpWcDk8kjA488nLkU4AA9Az9C6nDAOpcuT8suL+/+AjxSZTL7P6DVIT5bytdKG4gA3dkE4GASIg5oGW22d/a0WpskpPgYElItKd4FGvMX7yRN4v/sZZSJwDhIljMDYHxYFm8u2XuTBAxUfFtt0c8NnIGTxvj7Rw541DWy6iM2w68KsZI9og4FXhPD8lsw+sE6n+NMW9kxkZA5k/L1iD5DLb83rVdPZg3EBfP5U=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: influxdb-ds-secret
      namespace: automation
    type: Opaque
